### ISSUE TITLE
[Bug]: Running test with flag --watch fails

### ISSUE THREAD

**Issue by yarden-slon** [kubeshop/testkube-docker-action#6]
### What happened?

When I try to run a test with the flag --watch, the test completes successfully. However, the workflow fails with the error:
```
retry count exceeeded, there are no active pods with given id=63b2bcf099c8a316112e70c2-scraper
``` 
I expect that once the pod finished running, I won't get any errors and will see a successful run

### Version

1.0.0 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vsukhin** [comment]
Hey, @yarden-slon Just to confirm your configuration  - you use container executor with your own image and you provide artifacts options for scraping test reports?

**Comment by yarden-slon** [comment]
@vsukhin, I'm using container executor, but I'm not using any artifacts options
This is my executor (no feature of artifacts)
```
name: locust-executor
executor:
  executortype: container
  image: my_image:latest
  imagepullsecrets:
  - name: gar-secret
  command:
  - locust
  - --headless
  args: []
  types:
  - locust/test
  uri: ""
  jobtemplate: ""
  labels:
    app.kubernetes.io/managed-by: Helm
  features: []
executions: null
```
